
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcyhaepudiahrjrxltsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjeWhhZXB1ZGlhaHJqcnhsdHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDMyNDQsImV4cCI6MjA2MDAxOTI0NH0.4Yf4pFjzMteTG8y5CmL38dHiwIazBWzTbD3oU_jCKfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
