
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tcyhaepudiahrjrxltsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjeWhhZXB1ZGlhaHJqcnhsdHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDMyNDQsImV4cCI6MjA2MDAxOTI0NH0.4Yf4pFjzMteTG8y5CmL38dHiwIazBWzTbD3oU_jCKfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined
  }
});

// Define the database types based on our schema
export type Database = {
  public: {
    Tables: {
      products: {
        Row: {
          id: string;
          name: string;
          description: string;
          price: number;
          discount_price: number | null;
          images: string[];
          category: string;
          tags: string[] | null;
          featured: boolean;
          bestseller: boolean;
          in_stock: boolean;
          stock_quantity: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description: string;
          price: number;
          discount_price?: number | null;
          images: string[];
          category: string;
          tags?: string[] | null;
          featured?: boolean;
          bestseller?: boolean;
          in_stock?: boolean;
          stock_quantity?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          price?: number;
          discount_price?: number | null;
          images?: string[];
          category?: string;
          tags?: string[] | null;
          featured?: boolean;
          bestseller?: boolean;
          in_stock?: boolean;
          stock_quantity?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          name: string | null;
          email: string | null;
          phone: string | null;
          role: string;
          wishlist: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name?: string | null;
          email?: string | null;
          phone?: string | null;
          role?: string;
          wishlist?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string | null;
          email?: string | null;
          phone?: string | null;
          role?: string;
          wishlist?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          user_id: string;
          total: number;
          status: string;
          payment_method: string | null;
          payment_status: string;
          shipping_address: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          total: number;
          status?: string;
          payment_method?: string | null;
          payment_status?: string;
          shipping_address: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          total?: number;
          status?: string;
          payment_method?: string | null;
          payment_status?: string;
          shipping_address?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          quantity: number;
          price: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id: string;
          quantity: number;
          price: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string;
          quantity?: number;
          price?: number;
          created_at?: string;
        };
      };
      collections: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          image: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          image?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          image?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      collection_items: {
        Row: {
          id: string;
          collection_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          collection_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          collection_id?: string;
          product_id?: string;
          created_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
  };
};
